dbVenta-cnx: server=DESKTOP-CRJD420\SQLEXPRESS; database=dbVenta; integrated security=true;TrustServerCertificate=True;
url-base-servicio-stock: https://localhost:7065
log-mongo-server-db: mongodb://localhost:27017/dbLogs
log-mongo-db-collection: logs-ventas
dbPago-cnx: server=DESKTOP-CRJD420\SQLEXPRESS; database=dbPago; integrated security=true;TrustServerCertificate=True;
url-base-servicio-paago: https://localhost:5287
