dbVenta-cnx: server=DESKTOP-T9JDKHK; database=db_venta; integrated security=true;TrustServerCertificate=True
url-base-servicio-stock: https://localhost:7065
log-mongo-server-db: mongodb://localhost:27017/dbLogs
log-mongo-db-collection: logs-ventas
