dbVenta-cnx: server=DESKTOP-T1M4PN6; database=db_venta; integrated security=true;TrustServerCertificate=True
url-base-servicio-stock: https://localhost:7065
url-base-servicio-pago: https://localhost:7063
log-mongo-server-db: mongodb://localhost:27017/dbLogs
log-mongo-db-collection: logs-ventas
