dbVenta-cnx: server=DESKTOP-CRJD420\SQLEXPRESS; database=dbVenta; integrated security=true;TrustServerCertificate=True;
url-base-servicio-stock: https://localhost:7065
log-mongo-server-db: mongodb://localhost:27017/dbLogs
log-mongo-db-collection: logs-ventas
dbPago-cnx: server=DESKTOP-CRJD420\SQLEXPRESS; database=dbPago; integrated security=true;TrustServerCertificate=True;
url-base-servicio-pago: http://localhost:5287/
dbEntregas-cnx: mongodb://127.0.0.1:27017/?retryWrites=true&loadBalanced=false&connectTimeoutMS=10000
BootstrapServers: 127.0.0.1:9092
